### ISSUE TITLE
How to use with python3

### ISSUE THREAD

**Issue by aruldd** [mbachry/mosquitto_pyauth#7]
I have written a module in python3. I can see the plugin can import from only from python 2 folder. I have trouble setting the python path.  Any help will be appreciated.

**Comment by mbachry** [comment]
Hi! Python 3 is now supported. Check out README. All you need to do is make sure you have python3 headers installed (eg. `apt install python3-dev` under Ubuntu) and compile with `make PYTHON_VERSION=3.6` (or whatever version you use).

I hope it works fine for you. Enjoy!
